name: water-scarcity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - tqdm
  - scikit-learn
  - keras
  - xgboost
  - lightgbm
  - matplotlib
  - logging
  - pip
  - pip:
      - tensorflow
